# coding: utf-8
# Baseline generated by sqlacodegen sqlite:////var/www/phpliteadmin/leverage.sqlite

from sqlalchemy import create_engine

from sqlalchemy.orm import sessionmaker

from sqlalchemy.ext.declarative import declarative_base

from sqlalchemy import Column, Integer, MetaData, Table, Text
from sqlalchemy.sql.sqltypes import NullType


engine = create_engine('sqlite:////var/www/phpliteadmin/leverage.sqlite')
Session = sessionmaker(bind=engine)
session = Session()

Base = declarative_base()
metadata = Base.metadata


t_campaign_info = Table(
    'campaign_info', metadata,
    Column('campaign_id', Integer),
    Column('election_year', Integer),
    Column('election_cycle', Text),
    Column('candidate_id', Integer),
    Column('candidate_position', Text),
    Column('candidate_party', Text)
)


t_campaign_summary = Table(
    'campaign_summary', metadata,
    Column('campaign_id', Integer),
    Column('summary_value', Integer),
    Column('summary_level', Text),
    Column('summary_type', Text)
)


t_candidate_info = Table(
    'candidate_info', metadata,
    Column('candidate_id', Integer),
    Column('candidate_name', Text)
)


t_sqlite_stat1 = Table(
    'sqlite_stat1', metadata,
    Column('tbl', NullType),
    Column('idx', NullType),
    Column('stat', NullType)
)
